brew "bat"
brew "fzf"
brew "stow"
vscode "dbaeumer.vscode-eslint"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "linhmtran168.mac-ca-vscode"
vscode "mattpocock.ts-error-translator"
vscode "rangav.vscode-thunder-client"

